### ISSUE TITLE
error with "Genomic region out of bounds"

### ISSUE THREAD

**Issue by shuzhangcourage** [ysora/stripenn#1]
Hi Sora,
Thx for your great "Stripenn", very good tool to use, easy install also parameters. 
But I met an error, this came from Chr2 hg38. I am not good at debug by myself, I checked that "util.py" seems chromosome size information is done direct from UCSC, so I didn't figure this error out. BTW, some chromosome are work, others are not... 
Have you met that error before?  Could you please tell me what should I do to figure this out? 

Thanks a lot!
Shu

The error is : 
Traceback (most recent call last):
  File "/usr/users/szhang3/Software/Python-3.8.0/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/usr/users/szhang3/Software/Python-3.8.0/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/users/szhang3/Software/Python-3.8.0/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/usr/users/szhang3/Software/Python-3.8.0/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/usr/users/szhang3/Software/Python-3.8.0/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/users/szhang3/Software/Python-3.8.0/lib/python3.8/site-packages/src/getStripe.py", line 780, in iterate_idx
    right_obs = self.unbalLib.fetch(y_coord,x_coord)
  File "/usr/users/szhang3/.local/lib/python3.8/site-packages/cooler/core.py", line 573, in fetch
    i0, i1, j0, j1 = self._fetch(*args, **kwargs)
  File "/usr/users/szhang3/.local/lib/python3.8/site-packages/cooler/api.py", line 385, in _fetch
    region2 = parse_region(region2, self._chromsizes)
  File "/usr/users/szhang3/.local/lib/python3.8/site-packages/cooler/util.py", line 181, in parse_region
    raise ValueError("Genomic region out of bounds: [{}, {})".format(start, end))
ValueError: Genomic region out of bounds: [242150000, 242200000)
"""

**Comment by ysora** [comment]
Shu, Thanks for having interests in Stripenn.
To be honest, I didn't notice that error.
Could I get your cooler or .hic file for chromosome 2 to reproduce the error?
Thank you so much.

Sincerly,
Sora
________________________________
From: Shu Zhang ***@***.***>
Sent: Friday, April 23, 2021 9:37 AM
To: ysora/stripenn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [ysora/stripenn] error with "Genomic region out of bounds" (#1)


Hi Sora,
Thx for your great "Stripenn", very good tool to use, easy install also parameters.
But I met an error, this came from Chr2 hg38. I am not good at debug by myself, I checked that "util.py" seems chromosome size information is done direct from UCSC, so I didn't figure this error out. BTW, some chromosome are work, others are not...
Have you met that error before? Could you please tell me what should I do to figure this out?

Thanks a lot!
Shu

The error is :
Traceback (most recent call last):
File "/usr/users/szhang3/Software/Python-3.8.0/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
r = call_item()
File "/usr/users/szhang3/Software/Python-3.8.0/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in call
return self.fn(*self.args, **self.kwargs)
File "/usr/users/szhang3/Software/Python-3.8.0/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in call
return self.func(*args, **kwargs)
File "/usr/users/szhang3/Software/Python-3.8.0/lib/python3.8/site-packages/joblib/parallel.py", line 262, in call
return [func(*args, **kwargs)
File "/usr/users/szhang3/Software/Python-3.8.0/lib/python3.8/site-packages/joblib/parallel.py", line 262, in
return [func(*args, **kwargs)
File "/usr/users/szhang3/Software/Python-3.8.0/lib/python3.8/site-packages/src/getStripe.py", line 780, in iterate_idx
right_obs = self.unbalLib.fetch(y_coord,x_coord)
File "/usr/users/szhang3/.local/lib/python3.8/site-packages/cooler/core.py", line 573, in fetch
i0, i1, j0, j1 = self._fetch(*args, **kwargs)
File "/usr/users/szhang3/.local/lib/python3.8/site-packages/cooler/api.py", line 385, in _fetch
region2 = parse_region(region2, self._chromsizes)
File "/usr/users/szhang3/.local/lib/python3.8/site-packages/cooler/util.py", line 181, in parse_region
raise ValueError("Genomic region out of bounds: [{}, {})".format(start, end))
ValueError: Genomic region out of bounds: [242150000, 242200000)
"""

**Comment by ysora** [comment]
Hi Shu, I guess it was the index error occurred during the stripiness calculation, is that correct?
To calculate the stripiness, it uses pixel information near the candidate stripe. 
I think the index of right-hand background exceeded the Chr2 size.
I corrected the bug (ver 1.1.50), and if you have same problem again, please let me know.

**Comment by shuzhangcourage** [comment]
> Hi Shu, I guess it was the index error occurred during the stripiness calculation, is that correct?
> To calculate the stripiness, it uses pixel information near the candidate stripe.
> I think the index of right-hand background exceeded the Chr2 size.
> I corrected the bug (ver 1.1.50), and if you have same problem again, please let me know.
