### ISSUE TITLE
Stripenn Score crashes - positional argument bfilter missing

### ISSUE THREAD

**Issue by cvahlensieck** [ysora/stripenn#3]
Hi,
Thank you so much for supplying such an excellent tool!

When calling stripenn score, the cli throws the following error.

`stripenn score --cool input.mcool::resolutions/10000 --norm KR -c mega_features.csv`

        Traceback (most recent call last):
          File "/opt/jupyterhub/bin/stripenn", line 8, in <module>
            sys.exit(main())
          File "/opt/jupyterhub/lib/python3.9/site-packages/src/cli.py", line 59, in main
            app()
          File "/opt/jupyterhub/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
            return get_command(self)(*args, **kwargs)
          File "/opt/jupyterhub/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
            return self.main(*args, **kwargs)
          File "/opt/jupyterhub/lib/python3.9/site-packages/click/core.py", line 1053, in main
            rv = self.invoke(ctx)
          File "/opt/jupyterhub/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
            return _process_result(sub_ctx.command.invoke(sub_ctx))
          File "/opt/jupyterhub/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
            return ctx.invoke(self.callback, **ctx.params)
          File "/opt/jupyterhub/lib/python3.9/site-packages/click/core.py", line 754, in invoke
            return __callback(*args, **kwargs)
          File "/opt/jupyterhub/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
            return callback(**use_params)  # type: ignore
          File "/opt/jupyterhub/lib/python3.9/site-packages/src/cli.py", line 55, in scoring
            score.getScore(cool, coordinates,norm,numcores,out,mask)
          File "/opt/jupyterhub/lib/python3.9/site-packages/src/score.py", line 53, in getScore
            obj = getStripe.getStripe(unbalLib, resol, 10, 8, 2.5, all_chromnames, chromnames, all_chromsizes, chromsizes,core)
        TypeError: __init__() missing 1 required positional argument: 'bfilter'

My coordinate table is:
chr     pos1    pos2    chr2    pos3    pos4
17      40510001        40550000        17      40350001        40550000

The mcool file works with stripenn compute without problems.

Thanks!
Christian

**Comment by ysora** [comment]
Hi Christian,
Sorry for the late response.
I am currently on vacation and will be back in the mid of February.
Then I can look into the error.
Sorry for being late.

Sora

**Comment by ysora** [comment]
HI Christian, 
The bug was fixed in a new version of Stripenn 1.1.65.5.
Thanks.

Sora

**Comment by ysora** [comment]
Hi Katharina, 

Thanks for reporting the bug.
The bug has been fixed in Stripenn version 1.1.65.7.
Thanks!

Sora

**Comment by khayer** [comment]
Sora, it is all working now! Thank you so much
